### ISSUE TITLE
Question about timeline for 2.3

### ISSUE THREAD

**Issue by brettshumaker** [miled/wordpress-social-login#102]
Just curious if there's an estimated release date for 2.3. I'm looking to be able to hook into line 333 in `/includes/widgets/wsl.complete.registration.php` from version 2.2.3. I've got some additional fields I'd like to get from the user at registration.

If there's another way to achieve this - outside of editing that file directly - please let me know.

Thanks!

**Comment by ArondeParon** [comment]
:+1:Facebook integration as it is right now, is close to useless. A simple update on Wordpress.org would suffice.
