### ISSUE TITLE
Facebook login doesn't return user's email field - maybe due to API changes?

### ISSUE THREAD

**Issue by Pixelatic** [miled/wordpress-social-login#103]
Hi, it appears Facebook login is not returning the user's email field - maybe due to recent API changes.

From https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/
"Fewer default fields for faster performance: To help improve performance on mobile network connections, we've reduced the number of fields that the API returns by default. You should now use the ?fields=field1,field2 syntax to declare all the fields you want the API to return."

Another affected plugin https://wordpress.org/plugins/super-socializer/changelog/
"[Bugfix] Facebook Login was unable to fetch email and some other profile data of user due to recent changes introduced in FB JS SDK by Facebook"

The issue results in WordPress Social Login creating a new account for existing users instead of logging them in, as noted here https://wordpress.org/support/topic/fb-login-creates-new-account-instead-of-logging-in

When connected to Facebook via WordPress Social Login's Authentication Playground, I can see Provider user ID, Photo URL, Display name are being returned, however Email is empty.

From reading the plugin code it seems WordPress Social Login uses the hybridauth library's Facebook provider to connect to https://graph.facebook.com/v2.0/me for user profile data.

If I request https://graph.facebook.com/v2.0/me via the Authentication Playground's Connected Adapter Console, this returns an array containing only name and id, not email.

If I request https://graph.facebook.com/v2.0/me/?fields=name,email this returns an array containing name, id and email. Hoping this will be a minor fix to resolve.

Regards, David

**Comment by miled** [comment]
Since this repo is far ahead of the current release, I tried to fix this issue on wordpress.org dev repo. Would you give it a try and see if it works for you.

https://wordpress.org/plugins/wordpress-social-login/developers/ > **Other Versions** :  Development Version.

Thank you!

**Comment by Pixelatic** [comment]
Same issue when using the development version... WordPress Social Login creates a new account for existing users when authenticating using Facebook. The new users emails look like this: cc0c72e9880e05c9b38fff2efdc8a107@example.com.

**Comment by Pixelatic** [comment]
Possibly related: https://github.com/hybridauth/hybridauth/issues/509

**Comment by ftena** [comment]
This issue is related to commit miled/wordpress-social-login@720aaae311, isn't it?

But I don't see the plugin updated in wordpress.org and there are some bug reports opened (https://wordpress.org/support/plugin/wordpress-social-login) talking about this issue.

Any update planned?

**Comment by vmetzger09** [comment]
I'm not using WordPress; instead, I'm using the CakePHP framework along with HybridAuth for social_login, but a I also experience the exact same problem - only Provider, user ID, Photo URL, Display name are being returned while Email is empty.

Any word on an update to HybridAuth that circumvents this issue? 

Thanks

**Comment by vmetzger09** [comment]
Just answered my own question above: The affected HybridAuth PHP functions used by WordPress (as well as CakePHP in my case) have been recently updated to properly deal with this issue related to the Facebook v2.4 API... you can download the corrected HybridAuth Facebook.php component here:

https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Providers/Facebook.php

Use the contents of the above Facebook.php HybridAuth component to replace your "Facebook.php" file.  I'm using the CakePHP 2.x framework, so I replaced my "Facebook.php" file located here:

/var/www/html/app/Vendor/hybridauth/Hybrid/Providers/Facebook.php

Based on your configuration and which software HybridAuth is interfacing with, your path may be different.  After updating "Facebook.php" with the latest, corrected version, I am now able to retrieve ALL of the Facebook User Fields, including email, etc.

Happy Coding!

~ \/ 1 /\/ C 3

**Comment by dappi** [comment]
So is this going to be fixed or not? Seems vmetzger09 has solution for this

**Comment by ihorvorotnov** [comment]
@miled if you're busy I can update it and run some tests, followed by a PR (have some free time this week). Let me know what you think so we don't do the same work.

**Comment by jordantoen** [comment]
@ihorvorotnov , @miled I'm facing the same problem. Are there any news about it?
I can help too.

**Comment by beeriz** [comment]
I'm having the same issue using the latest version, any idea how to resolve this?
Facebook is not sending email but instead facebook_nickname@example.com

Thanks

**Comment by mastershas** [comment]
@miled  I am reading this thread for a long time since last posted. But, I would like to draw attention of authors and my observations. I think the plugin is setting a default email i.e username@example.com when the provider is not returning email. When I tried to create a user using facebook id which was registered using mobile, the email registered in website was like username@example.com.

**Possible Solution**
Can it be done by adding a condition by which the email input field should appear in the bouncer page if the provider did not return any email. Once the user fills email, we can send a confirmation mail to the user account and redirect to the account active page similarly as buddypress does during the time of registration.

Any lead would be appreciated. I think this issue is very important to consider..
