### ISSUE TITLE
Link my account - causes username already exists error

### ISSUE THREAD

**Issue by kingafrojoe** [miled/wordpress-social-login#104]
When signing in with Facebook you get the screen for.
Already have an account?
or
New to our website?

If you do "Link my account" then enter the username and password you get the error:
"An error occurred while creating a new user: Sorry, that username already exists!"

But is should just update the user not try to create a new one.

**Comment by katipierson** [comment]
Hello i have the same problem. How do you solved it?

**Comment by kingafrojoe** [comment]
I did fix it in my fork. This fix was merged into the main branch, so installing the latest version from this repo should fix your problem.

**Comment by katipierson** [comment]
Oh the Facebook-Account needs the same E-Mail-Adresse like the Wordpress-Account.

**Comment by oivinds** [comment]
Same problem here!

**Comment by katipierson** [comment]
@oivinds The Facebook-Account needs the same E-Mail-Adresse like the Wordpress-Account.
