### ISSUE TITLE
Connect with VKontakte set ID user in display name and nickname

### ISSUE THREAD

**Issue by misterblacker** [miled/wordpress-social-login#107]
Hi,
When I try to connect with Vkontakte, WSL sets ID name in wordpress display name field, and I see next message: "You are logged in as id19893****. Could you help me to fix this problem?

http://imgsave.ru/?v=2015-08-18_kh159tmwoxrja8fel6a0knjho.jpg

http://imgsave.ru/?v=2015-08-18_81t49gdg89fql250je0hjdsfd.jpg

http://imgsave.ru/?v=2015-08-18_rqr1y6yopsnvtuz06q51058j8.jpg

http://imgsave.ru/?v=2015-08-18_pb86tytom956lqr60bu08b423.jpg

**Comment by YuriyPonomarov** [comment]
Try to add this hook to wp-social-login.php:
// VK DISPLAYNAME HOOK
add_action('user_register','d_change_display_name');
function d_change_display_name( $user_id ) {
    $info = get_userdata( $user_id );
	$args = array(
		'ID' => $user_id,
		'display_name' => $info->first_name . ' ' . $info->last_name
	);
    wp_update_user( $args );
}
