### ISSUE TITLE
Conflicts with Wordpress Social Iinvitations 

### ISSUE THREAD

**Issue by gaborkukucska** [miled/wordpress-social-login#109]
Hi everyone,

I have found that WSL would encounter an error and unable to login users if the newest version (v.2.5.6.) of WSI is installed. Upon contacting their support told me:

"the problem is social login it's using an old version of Hybridauth library that is not including the logger file. There is nothing I can do about it"

The original PHP error:

[error] 1250#0: *76727 FastCGI sent in stderr: "PHP message: PHP Fatal error: Class 'Hybrid_Logger' not found in /var/www/wp-content/plugins/wordpress-social-invitations/hybridauth/hybridauth/Hybrid/Auth.php on line 238" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: mysite.com, request: "POST /wp-login.php?action=wordpress_social_authenticated&provider=Google&mode=login HTTP/1.1", upstream: "fastcgi://unix:/tmp/dmc.sock:", host: "www.mysite.com", referrer: "https://www.mysite.com/wp-login.php?action=wordpress_social_authenticate&mode=login&provider=Google&redirect_to=https%3A%2F%2Fwww.mysite.com%2F&redirect_to_provider=true"

Let me know what you think. Is there an easy way to update the Hybridauth library?

**Comment by fuchsws** [comment]
This still occurs in version 2.3 - any idea if this will/can be fixed?
