### ISSUE TITLE
Does not work on non-standard port

### ISSUE THREAD

**Issue by lukos** [miled/wordpress-social-login#112]
I have wordpress running on port 8001 because it using a tunnel. Wordpress social login hangs on return from authentication as the code generates a 304 redirect to something like http://mysite.com:8001:8001/wp-login.php.....

This is caused by the code in Hybrid_Auth::getCurrentUrl() which assumes that the HTTP_HOST does not contain the port number (it does). It then adds the port number into the URL as a string concatentation (surely there is a class for this kind of thing?).

I would raise this on the hybridauth project but their latest version of the file already has some kind of change applied and I don't know whether it is a copy-and-paste job into wsl or not.

Thanks

**Comment by coldacid** [comment]
Having the very same problem ourselves.
