### ISSUE TITLE
Pie Register and WP Social Login

### ISSUE THREAD

**Issue by omercan** [miled/wordpress-social-login#114]
Hi,

When I combined Pie Register and WP Social Login plugin, I could not save social profiles to database. So I'm getting infinite redirect pages. When I disable the Pie Register, everything is okey. 

How can I overcome from this issue?

Omercan

**Comment by ihorvorotnov** [comment]
I can't even find that plugin (Pie Register) in WordPress.org plugin repository. Where can we see its code?

**Comment by omercii** [comment]
https://github.com/wp-plugins/pie-register/

Here is it.

**Comment by ihorvorotnov** [comment]
I quickly checked the code, looks like that plugin heavily modifies native registration and login process. It's a lot to debug. You should also ask plugin developer for help. But there's no issues in it's GitHub repo so you should contact him directly, somehow. I'll install both plugins on my local test site and see if there are any errors / conflicts but no promises.

**Comment by omercii** [comment]
Thank you, I also send message to pie registers developer.

If you test the both plugins on your local test, i will apreciate it!

9 Eki 2015 Cum 15:43 tarihinde Ihor Vorotnov <notifications@github.com>
şunu yazdı:
