### ISSUE TITLE
Password field as plain text input when linking accounts

### ISSUE THREAD

**Issue by sanderaido** [miled/wordpress-social-login#127]
After authenticating with a new social account and wanting to link to an existing account, the password field is a simple text input. This is particularly bad if the user has a stored password for the account, which will be visible in plain sight.

![screen shot 2015-12-21 at 14 43 42](https://cloud.githubusercontent.com/assets/9868517/11931036/af5cd926-a7f1-11e5-9d7e-484c0cbe3eb1.png)

**Comment by madvik** [comment]
+1
I have the same problem !

**Comment by lennynld** [comment]
any progress?
