### ISSUE TITLE
Login With Email When Linking Accounts

### ISSUE THREAD

**Issue by krispy1298** [miled/wordpress-social-login#139]
My site has email login enabled with the following:

```
add_filter('authenticate', array($this, 'allowEmailLogin'), 20, 3);
  public static function allowEmailLogin( $user, $username, $password ) {
    if ( is_email( $username ) ) {
      $user = get_user_by( 'email', $username );
      if ( $user ) {
        $username = $user->user_login;
      }
    }
    return wp_authenticate_username_password( null, $username, $password );
  }
```

When existing users try to login via Social and link to existing account, they cannot use their email to login in the gateway.

**Comment by dabodude** [comment]
+1 PLEASE!!!!

**Comment by Lindsayanng** [comment]
What is the error that is returned?

**Comment by dabodude** [comment]
This problem also happens to me when people try to associate their social account to an existing WordPress account.

You are asked to input the username of the wordpress account to associate, but you can't use the email instead.

Try: https://goo.gl/UEWSl1

**Comment by Lindsayanng** [comment]
Can you expand on "the problem"...? What actually happens? Give steps for how it can be reproduced and what actual issues you are seeing. (not interested in creating an account on your site)

**Comment by dabodude** [comment]
You can see with detail right here, I made a screencast:

http://youtu.be/9o3FC5Sk4cY?hd=1

**Comment by Lindsayanng** [comment]
Ok. So this happens because the above filter words on the authenticate() hook but this plugin uses wp_set_cookie() to authenticate so the filter isn't even touching this. 

That means your above code is going to have to be rewritten so that it works with wp_set_cookie() instead.

**Comment by dabodude** [comment]
Sorry, I think I got you confused by adding me to krispy1298's original post.

I'm not using any filter or function to enable email login in my store.

I simple wanted to request the developer to allow users to login/link account with either username or email. Not only username.
