### ISSUE TITLE
Problem in process

### ISSUE THREAD

**Issue by madvik** [miled/wordpress-social-login#141]
# Options:

Accept new registration : YES
Allow authentication : YES
Link user account : YES
Require E-mail : YES
Allow Username change : YES
Hook extra registration fields : YES
# Requirement:
1. Account already exist :
   - account_1@wp.com
   - account_2@wp.com
2. My account is  : account_1@wp.com
3. The logged  facebook account : account_2@wp.com
# Process:
1. I click on the widget "Facebook" ( `<?php do_action( 'wordpress_social_login' ); ?>` )
2. I click on "Link my account"
3. I connect with account_1@wp.com (login and password)
4. I am conected with account_2@wp.com /!\

No control exist between  the login and the facebook email address.

**Comment by Lindsayanng** [comment]
I am working on this issue right now actually. Basically right now priority is always being given to the social network's email address and it's ignoring any manually entered addresses (either via linking accounts OR creating new accounts). 

I am walking through the code now to see if this can be resolved easily. It seems that it checks to see if the email exists as a user and if it does it automatically authenticates for that user. It doesn't check to see if the email entered into the forms matches. We just need to run those checks and ask the user what they want to do. 

So ideally what would happen is you try to link your FB account (under account_2@wp.com ) with your site's account (under account_1@wp.com) it should do the following: 

1. Tell you that the email address associated to your site account does not match your fb authentication email 
2.  Ask you if you would like to update your account to match or use your site's email address 
3. If you choose to update the account to match, it would then tell you that an account already exists with that email, would you  like to link it.

**Comment by madvik** [comment]
@miled You solved the problem ?
