### ISSUE TITLE
Unable to translate string with variable: "You're now signed in with your %s account..."

### ISSUE THREAD

**Issue by dabodude** [miled/wordpress-social-login#142]
Unable to translate "You're now signed in with your %s account but you are still one step away of getting into our website"...

**Comment by Superfly-fr** [comment]
+1 here with French (for what it worth).
I've edited (poedit) the wordpress-social-login-fr_FR.po and translation was here but does not seem to be fired when displaying in the login box (after valid social login / with option to add email or change user mail / other texts and buttons are correctly translated).

![image](https://cloud.githubusercontent.com/assets/1899300/25710184/ce65527e-30eb-11e7-87c8-cfd663474d9d.png)

**Comment by Superfly-fr** [comment]
Ok, found out that if you compare widget code and translations you can notice there's a slight difference ('are' is missing in string ID).

In includes/widget/wsl.users.gateway.php
`<?php printf( _wsl__( "You're now signed in with your %s account but you **are** still one step away of getting into our website", 'wordpress-social-login' ), $provider ); ?>.`
In poedit, original (English) string :
You're now signed in with your %s account but **you still** one step away of getting into our website.

So I presume I can hack this temporarily by editing wsl.gateway.php (what I did: that's working still ... BAAAD) but would be better to make all the translation match ... I'd bet the pot file has a bad string ID)

Not sure what I can do to help here, just let me know.
