### ISSUE TITLE
An error occurred while creating a new user: Sorry, that username already exists!

### ISSUE THREAD

**Issue by ianferrell** [miled/wordpress-social-login#153]
When attempting to link an older account to one where the email is different on Facebook, this error occurs. If linking an account and the username and password are correct, why does it not automatically link?

For some reason the email of the Facebook and the WordPress account must match 100% for a link to be established. Is there a way around this?

**Comment by brainfork** [comment]
Account linking is broken with Google as well, the emails have to match or else the same error is displayed.

**Comment by afarber** [comment]
Unfortunately, I have the same issue

**Comment by mautematico** [comment]
Same issue here. Is anyone working on a PR to solve it?

I think we can use `Provider User ID` at first when linking, instead of matching email. And just keep provider email as a user_meta.

The best, I think, will be being able to link single wordpress account with as many social providers as user wants, no matter if user is using different emails on each social provider.

**Comment by pavankumarkatakam** [comment]
Now, im getting this issue.

**Comment by joesaundersak** [comment]
I am getting this error on my installation too... It seems to only allow one social account to be attached to each WP user account

**Comment by abegit** [comment]
It seems to allow me to sync to more than one social network.
I got this to work on [Bonoboville](https://Bonoboville.com)

But the email factor is true, I just had to change my email to match FB's and then re-attempted to sync my account. And It WORKED! Used Twitter, Google, and Facebook

**Comment by nova-ind** [comment]
I was having the same problem. Managed to fix it with this hook:
```
/**
 * Fix social login linking to existing account.
 *
 * @param array $userdata
 *
 * @return object|int|void
 */
function wsl_fix_account_link( $userdata ) {
	if ( isset( $_REQUEST['user_login'], $_REQUEST['user_password'] ) ) {
		$user = wp_authenticate_username_password( null, $_REQUEST['user_login'], $_REQUEST['user_password'] );
		if ( is_wp_error( $user ) ) {
			return $user;
		} else {
			return $user->ID;
		}
	}
}
add_filter( 'wsl_hook_process_login_delegate_wp_insert_user', 'wsl_fix_account_link' );
```
