### ISSUE TITLE
How about not asking for Facebook users' friend lists as default?

### ISSUE THREAD

**Issue by leehankyeol** [miled/wordpress-social-login#160]
Currently the plugin's default Facebook API scope include `user_friends`, which I think is not appropriate as a default option.

**Comment by mautematico** [comment]
I was unable to reproduce that default behavior. In my case, the plugin didn't ask me for my friends list.

P.S.: My friend list is private (I made it private a few years ago, when it was still possible).

**Comment by KevinMWalsh** [comment]
I think this is something that you configure within the facebook app that you provided the id and secret for. I remember choosing this when setting up the app. Head to https://developers.facebook.com/apps and change your settings for the app and see if that resolves this.

**Comment by Key1337** [comment]
There doesn't seem to be any way to do this from the Facebook dev app's side; seems they just decide there what permissions you're authorized to use from Facebook's point of view, and `user_friends` perm is part of the default set.

From what I can tell, WordPress Social defines the FB perms of 
`public $scope = [ 'public_profile', 'email' ];`
in the file
`Facebook.php`

and later these are overridden with
`"default_api_scope" => "email, public_profile, user_friends", `
in file
`wsl.providers.php`

I wish there were a way to set that override to just `"email, public_profile"` without having to hack the core plugin code, which I'm assuming gets overwritten with plugin updates.

Is there any way to accomplish this as a custom plugin that changes the array value? I found some info on how to customize plugins without hacking their core but cannot figure out how to implement the idea in this case to eliminate WordPress Social from requesting the `user_friends` permission. My website has no need to ask for their friends list...

[https://iandunn.name/2014/01/10/the-right-way-to-customize-a-wordpress-plugin/](url)

**Comment by belonog** [comment]
The set of requested permissions, including `user_friends`, is stored in the `wp_option` database table. This parameter is controlled in the plug-in via the Contacts extension. More information here [Plugin Documentation](http://miled.github.io/wordpress-social-login/userdata.html)
