### ISSUE TITLE
Wrong vkontakte Callback URL

### ISSUE THREAD

**Issue by mxite** [miled/wordpress-social-login#161]
> 1. Provide this URL as the Callback URL for your application: 
>    */wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=Vkontakte

VK reports this URL is wrong

*/wp-content/plugins/wordpress-social-login/hybridauth/ works fine (without "?hauth.done=Vkontakte" part)

**Comment by evanre** [comment]
Hello, if somebody else will search for this issue... You can setup VK Api without this callback url! WSL will work fine only with Application ID and Application Secret.
