### ISSUE TITLE
$SESSION Block Caching

### ISSUE THREAD

**Issue by akincansenol** [miled/wordpress-social-login#162]
Php Session's can hurt any cache method. That would be nice if storage change to cookie @miled 

Best,
Akın

**Comment by visualdatasolutions** [comment]
Hi Akin,

I had huge issues with PHP sessions on Firebox and Chrome when browser cache was enabled, and was tempted to modify the storage myself. On second thought I didn't make any changes to the HybridAuth class. My problem was solved by changing the authentication url and redirect url to WooCommerce's login page.  WooCommerce has a helper class and handles no-cache header better than wp-login.php.  The full details of the approaches I have tried and the working code are available in this post  [enabling browse cache and WordPress Social Login on Firebox and ](https://tagnmap.com/wp/enabling-browser-cache-wordpress-social-login-firefox-chrome/). I was amazed at the short and simple code, after the long hours debugging the issues. Hopefully this will help someone with similar problems. Given the popularity of WooCommerce, using WooCommerce login page may solve some of the PHP sessions problem. It is also worth considering to use WooCommerce login page by default, if WooCommerce is activated. 

I am not a security expert. My understanding is that Cookie is prone to man-in-the-middle attack and manipulation at the client side, especially when ssl is not used, and the cookie is transmitted in plain text. Firefox allows developers to modify and send raw headers, and the same feature can be abused. PHP session parameters are saved at the server side and are harder to hijack by comparison. What do you think?

**Comment by akincansenol** [comment]
Hello @visualdatasolutions ,

I just seeing your reply.  All I mean in this article [](https://pressjitsu.com/blog/wordpress-sessions-performance/)

Akın
