### ISSUE TITLE
Google/Plus import of contacts fails

### ISSUE THREAD

**Issue by alicam** [miled/wordpress-social-login#164]
There is a "typing error/mismatch" issue with importing contacts from a Google+ user.

https://github.com/miled/wordpress-social-login/blob/063587671500919348df3cac0d6d6b85af0ec339/hybridauth/Hybrid/Providers/Google.php

The database won't accept NULL values for profileURL or photoURL but these are being passed that way in the database UPDATE.

Looks very ugly with all these DB errors on the page for a user to see.

**Comment by KevinMWalsh** [comment]
Yes, and while the user gets an activation email and their profile shows up in the WP admin under Users, they only get these errors when trying to log in and the user does not show up in WSL's Users list.

**Comment by alicam** [comment]
So... is there a fix in sight?

Generally, I'd assume it was core functionality and a pretty basic thing to be have this sort of stuff working properly. What should my expectations be??

**Comment by afarber** [comment]
I am watching this repository for some time and I doubt there will be any fix.

There is unfortunately never any response by miled and there are 12 not integrated pull requests.

**Comment by visualdatasolutions** [comment]
Hi,

the plugin author seems to be busy in recent months. I am using the import contact feature and got similar error messages in the server log. I have made small changes to the data type definition for the import to work. You may have already done this as a work around. here is the link to my solution just in case someone is reading this thread looking for help. [Import User Contacts with WordPress Social Login](https://tagnmap.com/wp/import-user-contacts-wordpress-social-login/). 

The article is written for someone who is not a developer and who knows little about this plugin. apologies if it is boring to you and states the obvious. 

Some Facebook contacts may not allow export of their email address. As a result the email addresses are missing from the returned data. Google+ contacts may actually be from email or Android phone. so email and URLs could be missing too. 

The easy solution is to accept empty values, and allow user to login. What do you think? I will create a pull request for @miled to consider merging into the plugin. 

also as a reminder, PHP error messages should be turned off on a production server for security concerns. 

best. 

Oliver
