### ISSUE TITLE
Slack login

### ISSUE THREAD

**Issue by ekandreas** [miled/wordpress-social-login#165]
How do I integrate Slack as a login option to WordPress with WSL?

**Comment by afarber** [comment]
By adding Slack.php under hybridauth/Hybrid/Providers/ ;-)

**Comment by ekandreas** [comment]
Great! Perhaps this request will make someone more pro on auth to create one? :-)

**Comment by ekandreas** [comment]
But, it seems quite easy to create one...

**Comment by afarber** [comment]
https://github.com/hybridauth/hybridauth/blob/master/additional-providers/hybridauth-slack/Providers/Slack.php could be used as a start, however WSL uses slightly modified version of Hybridauth.
