### ISSUE TITLE
Login issue after updating to https

### ISSUE THREAD

**Issue by hemantprakash123** [miled/wordpress-social-login#170]
I have updated my from http to https. Now I am not able to login using google or fb.
I am getting an error. 
1. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Missing scheme: //www.carsangrah.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=Google

Learn more

Request Details
access_type=offline
scope=profile https://www.googleapis.com/auth/plus.profile.emails.read
response_type=code
redirect_uri=//www.carsangrah.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=Google
client_id=******.apps.googleusercontent.com
That’s all we know.

**Comment by afarber** [comment]
Allow https://www.carsangrah.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=Google as redirect URI in Google console.

**Comment by hemantprakash123** [comment]
Already did that. Still not working.
