### ISSUE TITLE
Facebook Graph API v2.0 reaching end-of-life

### ISSUE THREAD

**Issue by mboldt** [miled/wordpress-social-login#171]
I received an email from Facebook, noting that my website "has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences."

Are there plans to migrate to a supported Facebook Graph API version?

**Comment by qikkeronline** [comment]
@miled this is getting more relevant by the day, are you planning to pick this up? If not, we will have to migrate our sites to another social auth system (this plugin is great so we'd love to be able to use it still). Thanks for looking into it!

**Comment by fariazz** [comment]
This is quite scary..

**Comment by fariazz** [comment]
I've activated this new option and my FB login still works, so I guess we'll be fine for this upgrade.

![fb login](https://cloud.githubusercontent.com/assets/1313597/17199081/a57856dc-54bd-11e6-9e53-88c3627ed34b.JPG)

**Comment by mboldt** [comment]
@fariazz Maybe I'm missing something, but where did you find this option? All the settings for this plugin are under Settings -> WP Social Login afaict, and I don't see the API Version Upgrades option. I don't see the Settings -> Advanced in your screenshot. Is this some other plugin?

**Comment by liuhenry** [comment]
@mboldt The screenshot is from the Facebook apps dashboard (e.g. https://developers.facebook.com/apps/XXXXX/dashboard/). If the plugin isn't updated, that's the behavior that will happen anyway.

**Comment by mboldt** [comment]
Got it---thank you for the clarification, @liuhenry!
