### ISSUE TITLE
Missing filter hook: `wsl_hook_process_login_alter_user_id`

### ISSUE THREAD

**Issue by ollietreend** [miled/wordpress-social-login#175]
In the [developer authentication API documentation](http://miled.github.io/wordpress-social-login/developer-api-authentication.html) – specifically, during the documented actions for method `wsl_process_login_get_user_data()` – it says that the process of matching a social user profile with an existing WordPress user ID can be delegated to a custom function through use of a filter hook.

The documented hook name is `wsl_hook_process_login_alter_user_id`. However, a search of the codebase shows that [this filter does not exist](https://github.com/miled/wordpress-social-login/search?q=wsl_hook_process_login_alter_user_id).

Walking through the code for the `wsl_process_login_get_user_data()` method, it is clear that the filter was never implemented. There is a comment where the filter should be, but it isn't there. See this snippet from [lines 574–585 of `includes/services/wsl.authentication.php`](https://github.com/miled/wordpress-social-login/blob/063587671500919348df3cac0d6d6b85af0ec339/includes/services/wsl.authentication.php#L574-L585):

``` php
/* 4 Deletegate detection of user id to custom filters hooks */

/* 6. returns user data */

return array(
    $user_id,
    $adapter,
    $hybridauth_user_profile,
    $requested_user_login,
    $requested_user_email,
    $wordpress_user_id
);
```
### Solution

Add the filter hook `wsl_hook_process_login_alter_user_id` to the method. This should be added in two places due to a fork in the logic: line 441, and line 575.

``` php
$user_id = apply_filters( 'wsl_hook_process_login_alter_user_id', $user_id, $provider, $hybridauth_user_profile );
```

There is also a typo in the word "deletegate" which has been used throughout the code and documentation. I believe the intended word is "delegate".

**Comment by LuisEduardoPS** [comment]
I think it has something to do with my problem. Could you please help me with that?

https://github.com/miled/wordpress-social-login/issues/182
