### ISSUE TITLE
Using Android/iOS App webview with authentication

### ISSUE THREAD

**Issue by abdojapan** [miled/wordpress-social-login#179]
Hi,

I have an app with my website. When the user press the facebook or google+ login, I want to run the authentication process using my Android/iOS native libraries rather than the default one which will force the user to enter user/pass for the google or facebook account inside the webview even if he is logged in to facebook/google native application.

I can easily start the native authentication process by hooking javascript into the webview, but after the native authentication process, I want to proceed with the Woredpress Social Login 'The Authentication Process' from wsl_hook_process_login_after_hybridauth_authenticate to get exactly the same result as authentication from normal browser.

Is there a way to just override the 'Hybrid_Auth::authenticate()' stage to use the native one without disrupting the flow?

Thanks for advance.

**Comment by tarata** [comment]
i have same problem
browser ok native web app not work

have you an idea?

**Comment by akraturi** [comment]
Hi i have the same problem. Did anyone get any idea how to do so?
