### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by slaFFik** [miled/wordpress-social-login#181]
We ran a `php7cc`, and found this:

```
File: .../plugins/wordpress-social-login/hybridauth/Hybrid/thirdparty/OpenID/LightOpenID.php
> Line 393: Function argument(s) returned by "func_get_args" might have been modified
    func_get_args();
```

Might be both critical and not, depends on the context.

**Comment by Saboteur777** [comment]
Any progress on PHP7 compatibility? I got a reply from my hosting provider that the plugin is not compatible with it.

**Comment by Lucidize** [comment]
Bump.

Please update with a fix for PHP7 or inform if there will not be an update so that we can source an alternative. Many thanks.
