### ISSUE TITLE
Social Login Issue

### ISSUE THREAD

**Issue by Tickboxx** [miled/wordpress-social-login#185]
When users try to login they are now getting the following issue -

WordPress database error: [Column 'email' cannot be null]
INSERT INTO `wp_thfyfb4f0f_wsluserscontacts` (`user_id`, `provider`, `identifier`, `full_name`, `email`, `profile_url`, `photo_url`) VALUES (23, 'Facebook', '10153732373746933', 'Robert Good', NULL, 'https://www.facebook.com/app_scoped_user_id/10153732373746933/', 'https://graph.facebook.com/10153732373746933/picture?width=150&height=150')

It shows this for many users, so I am concerned that details can be seen that shouldn't be. This has only just started happening

**Comment by HenryHzz** [comment]
I had ran into the same problem. Seem to be because the facebook API has changed... the plugin can no longer get the email information... Unless someone comes up with a hack to fix this, it's no longer working.
