### ISSUE TITLE
Google: Authentication failed

### ISSUE THREAD

**Issue by gaurav112** [miled/wordpress-social-login#192]
I am getting this issue since last 2 days trying to figure the problem but no luck.

Oops! We ran into an issue.
Authentication failed. Either you have cancelled the authentication or Google refused the connection.
Authentication failed! Google returned an invalid code 4/xDid_D2DefHLkUldAp6CCbJNzS4FoBMHRdoMzn-Nov8
400. { “error” : “invalid_request” }

so can anyone please help me out to resolve this issue.

**Comment by shanepinnell** [comment]
I am seeing the same thing, any resolution yet?

**Comment by skylerah** [comment]
Running into the same issue.

**Comment by psyntium** [comment]
I've managed to fix this. Seems need to update the google token_url endpoint. These are the changes that I made to make this work:

Filename: [hybridauth/Hybrid/Providers/Google.php](https://github.com/miled/wordpress-social-login/blob/master/hybridauth/Hybrid/Providers/Google.php) line 31:
`$this->api->token_url = "https://www.googleapis.com/oauth2/v4/token";`

Filename: [hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php](https://github.com/miled/wordpress-social-login/blob/master/hybridauth/thirdparty/OAuth/OAuth2Client.php)
add these lines:
```
if (strpos($this->token_url, "googleapis") !== false)
	array_push($this->curl_header, 'Content-Type: application/x-www-form-urlencoded');
```
Before:
`$response = $this->request( $this->token_url, $params, $this->curl_authenticate_method );`

Replace this line:
`if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );`
With:
```
if($params) {
	if (in_array('Content-Type: application/x-www-form-urlencoded', $this->curl_header))
		curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query($params) );
	else
		curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );
}
```

**Comment by gaurav112** [comment]
Thanks this did the trick !!

**Comment by samvthom16** [comment]
Having the same issue since the last two days. The above changes makes it return this error:

The requested URL was not found on this server. That’s all we know.

**Comment by haluvibe** [comment]
So how long will this take to make it to a version update, I don't want to hack the plugin, just want to have to update it

**Comment by afarber** [comment]
The author hasn't replied to anything since over 1 year.

**Comment by haluvibe** [comment]
oh

**Comment by haluvibe** [comment]
hacking it is then

**Comment by haluvibe** [comment]
I confirm that psyntium fixes this issue. Thank you for the fix and the very clear instructions.
