### ISSUE TITLE
Warning: do not use WSL plugin!

### ISSUE THREAD

**Issue by afarber** [miled/wordpress-social-login#195]
I am subscribed over 1 year to this GitHub page and haven't seen the author ever reply to questions or accept pull requests.

The author probably has reasons to do that and I respect that.

But before you invest your time into WSL plugin, you should consider that for now this software seems to be abandoned. 

And there are several known issues with WSL plugin - for which you will receive no support, once you hit them.

**Comment by deepdivingspearo** [comment]
Well that happens, projects come and go. Someone capable need to fork the project then I guess, so the community can pick up the project and take it forward. Any takers?

**Comment by Pokerkoffer** [comment]
there are so many pull requests and have a look in the graph section, i think the community can maintain this project. But there is someone needed who takes care of managing this project.

**Comment by afarber** [comment]
A good start would be to remove the customized HybridAuth currently used in WSL plugin.

**Comment by oddsized** [comment]
Very nice plugin, many thanks to the authors! Hope I'm not the last joining this thread. Just started working with WSL and love the userlist backend. 
Github and Linkedin both seem to work well so I like to keep this plugin running and make some effort in checking out how to get Facebook, Google and other api's connecting correctly again. 
> Maybe the hybridAuth part is not the main problem, i think so because other api's still work well. Some api responses are changing in time, scheduled (api focussed) plugin updates with community support are needed.  

Let me know if you 2 would like to put some effort in the WSL plugin, maybe we can make it work great again.

**Comment by danimalweb** [comment]
This seems like the best plugin given what I found. It would be great if the community took it forward.

The code base seems relatively clean and well documented.

Are there other plugins out there which are as good as this one?

**Comment by afarber** [comment]
I am closing my "issue" because the author (miled) is thankfully back and is merging pull requests.
