### ISSUE TITLE
500 error logs, no solution on google

### ISSUE THREAD

**Issue by tzookb** [miled/wordpress-social-login#206]
Hey guys,

tried to look for in the troubleshooting but nothing...

got this log on my error log, when I get 500:

```
#0 /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Provider_Model.php(90): Hybrid_Providers_Facebook->initialize()
#1 /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Provider_Adapter.php(102): Hybrid_Provider_Model->__construct('Facebook', Array, Array)
#2 /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Auth.php(212): Hybrid_Provider_Adapter->factory('Facebook', Array)
#3 /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Auth.php(149): Hybrid_Auth::setup('Facebook', Array)
#4 /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/includes/services/wsl.authentication.php(219): Hybrid_Auth::authenticate('Facebook', Array)
#5 /home/yourpriv/10xforum.com/wp-content in /home/yourpriv/10xforum.com/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Providers/Facebook.php on line 64
```

**Comment by namsir** [comment]
Same here,

 [error] [client 66.216.132.98] PHP Parse error:  syntax error, unexpected '[' in /www/curlupapp.com/htdocs/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Providers/Facebook.php on line 34, referer: http://www.curlupapp.com/swplogin?action=wordpress_social_authenticate&mode=login&provider=Facebook&redirect_to=http%3A%2F%2Fwww.curlupapp.com%2F

**Comment by namsir** [comment]
Found out that our production is running 5.3 and i think your plugin was written in 5.6+. Are you able to make it compatible with php 5.3 ?

**Comment by SalvadorBordon** [comment]
Good morning,

I have the same error. please, do you know the solution?

I have in server prod the php version 5.3.3 and in development server the version php 5.5.12.

In development all is ok, I don't have any problem, bat in production I have this error in file log:

PHP Parse error: syntax error, unexpected '[' in /var/www/html/mysite/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Providers/Facebook.php on line 34,

Best regards.
