### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by bircaman** [miled/wordpress-social-login#211]
Parse error: syntax error, unexpected '[' in /home/bircahan/public_html/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Providers/Facebook.php on line 34

**Comment by jhpruim** [comment]
Same as issue #206.
I have also this problem after update to 2.3.3.

**Comment by SalvadorBordon** [comment]
Good mornig,

I have the same error. please, do you know the solution?

I have in server prod the php version 5.3.3 and in development server the version php 5.5.12.

In development all is ok, I don't have any problem, bat in production I have this error in file log:

PHP Parse error:  syntax error, unexpected '[' in /var/www/html/mysite/wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/Providers/Facebook.php on line 34,

Best regards.

**Comment by SalvadorBordon** [comment]
The solution was , update php version in  server to 5.6 and change/assign value to var zone-time in php.ini
