### ISSUE TITLE
Which branch/tag to use for the current released v2.3.3 in WP repository?

### ISSUE THREAD

**Issue by ziogaschr** [miled/wordpress-social-login#215]
Hello, @miled.

Which branch/tag can I use for the current released v2.3.3 in the WP repository?
I would like to add [Authentiq](https://www.authentiq.com/) provider and some more fixes there.

> Authentiq is a new OAuth2/OIDC provider that offers passwordless authentication and keeps personal data on the phone instead of in the cloud.

Or, are you planning the next release at the WP repository to be the one from the current master branch?

Thanks,
Chris

**Comment by miled** [comment]
Unless something major occurs on v2.3.3 that would warrant a hot fix, my current plan's to move forward with the integration of hybridauth 3 on master branch. That said, if you want to add Authentiq, I can branch v2.3.3 here on Github too for you to do so.

**Comment by ziogaschr** [comment]
I'm preparing some PRs for v3, but this will take some more time so would be great to have it in v2 too.

**Comment by miled** [comment]
Okay. I made this branch from live code:

https://github.com/miled/wordpress-social-login/tree/v2

**Comment by ziogaschr** [comment]
Thanks a lot @miled.
