### ISSUE TITLE
Login redirect issue.

### ISSUE THREAD

**Issue by saurabhj91** [miled/wordpress-social-login#229]
Hi Team,

When i click on facebook/google to login and do not login it doesn't redirect to website/login page. It shows error. Please check the screenshots. 
1. https://prntscr.com/g3a91o
2. https://prntscr.com/g3a91m

**Comment by rubenrafaelmercado** [comment]
Hi. I have verified same problem in my site. I hope the below info can help:
Link in "Not Now":
http://mysite.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth_done=Facebook&error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=844c3430220e80bb245622980e51dc3a#_=_

Link in error window : http://mysite.com/wp-login.php?action=wordpress_social_authenticate&mode=login&provider=Facebook&redirect_to_provider=true#_=_
