### ISSUE TITLE
Blocking registrations blocks logins too

### ISSUE THREAD

**Issue by Daneel87** [miled/wordpress-social-login#23]
I use WSL to let my users register and login through google.

Setting "Accept new registration" OFF and "Allow authentication" ON my users can't login and the bouncer says no registration allowed.

**Comment by JimBoone** [comment]
I am having the same problem - Our membership is static but I get excessive number of robot registrations.  (reCAPTCHA is not free with TML anymore).   I decided to just manually process new registrations.   When I switch "Accept new registration" to OFF users that are already set up to use WSL get a message that registration is not allowed.   The previous issue was closed Was there a resolution?
