### ISSUE TITLE
The redirect_uri URL must be absolute (FB Login)

### ISSUE THREAD

**Issue by skimonkey** [miled/wordpress-social-login#241]
Get this error when trying to login via Facebook.
"The redirect_uri URL must be absolute"

the url (blanked out my client_id) is 

https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest&client_id=xxxxxxxxxxxxxxxx&state=9fca7be4258a4d1aed706cc761cb0880&response_type=code&sdk=php-sdk-5.4.4&redirect_uri=%2Fwp-content%2Fplugins%2Fwordpress-social-login%2Fhybridauth%2F%3Fhauth_done%3DFacebook&scope=email%2Cpublic_profile%2Cuser_friends

so I can see the redirect_uri param is relative. 
Are there any workarounds for this..?

**Comment by kogi-bac** [comment]
I too have been facing the same problem.
