### ISSUE TITLE
Plugin disable WordPress 4.9 Editor theme files

### ISSUE THREAD

**Issue by siamlottery** [miled/wordpress-social-login#245]
@miled 
When i am editing code in editor for the files of theme
like .php and got slowly load when submit.
Hope wordpress-social-login team will solved this soon!
Thank you.

**Comment by viruslovend** [comment]
I am having the same sort of problem – I cannot edit the main theme CSS or PHP files, I get a 530 error and it tells me to edit the file via FTP. 

When i disable plugin WordPress Social Login, Editing code in editor worked.

**Comment by siamlottery** [comment]
@NickIvanter @ziogaschr @hubdotcom
