### ISSUE TITLE
Wechat and weibo integration

### ISSUE THREAD

**Issue by alexlii1971** [miled/wordpress-social-login#246]
Hello,

Any plan to add WeChat and Weibo? if yes, please let me know what I can do, and I am very like to donate 100 US dollar for WeChat and weibo function.

Thanks.

Alex

**Comment by alexlii1971** [comment]
HELLO

Maybe wechat is much strange to you since it is not so global like Facebook and twitter.

I have two premium plugins of wechat login and payment gateway from another author, but really bad coding,   anyway you may know a lot the requirement and mechanism internally.

If you want integrate in wordpress-social-login, leave your email address here and I will sent.

**Comment by ZAZA316** [comment]
I am already login to wechat, and I want to know about receiving url message from other users.

**Comment by alexlii1971** [comment]
sorry, I do not understand, what you mean by “already login to we chat”? Do you mean login Wechat app on mobile, or login a site by wechat ?

What you mean receiving url message?  If you mean the url of stored message on wechat, I have to say, there is no messages stored.

But, if you registered an merchant or services account, you can publish post on your account backend.

Alex
