### ISSUE TITLE
This URI is not valid under Strict Mode. 

### ISSUE THREAD

**Issue by mdbootstrap** [miled/wordpress-social-login#259]
It looks like Facebook is about to change their policy soon:

> In March, we're making a security update to your app settings that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field below.This update comes in response to malicious activity we saw on our platform, and we want to protect your app or website by requiring a new strict mode for redirect URIs. Learn More

Here are 1 out of the 1 of your URIs that will be invalidated by this change.

https://mydomain.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth_done=Facebook

This URI is not valid under Strict Mode. Learn more
You can make this URI valid by adding it to the list of valid OAuth redirect URIs above

Is fix or workaround already available?

**Comment by neomax22** [comment]
I join the question, the plug-in stopped working with Facebook

**Comment by 5im5im** [comment]
I have the same problem, I couldn't figure out the correct redirect URL I should enter in FB.

**Comment by 5im5im** [comment]
I had to add the URLs without https then it worked:
http://mydomain.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth_done=Facebook
http://mydomain.com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=Facebook

So the url hint in the plugin-settings is misleading if you are using https.
