### ISSUE TITLE
Problem with Social Login to Facebook

### ISSUE THREAD

**Issue by Bigspecialk** [miled/wordpress-social-login#265]
In trying to setup Facebook login I get the below message.

Invalid Scopes: user_friends. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

It appears there is an issue in asking for the user_friends. 

Any ideas on how to fix?

**Comment by alexxgathp** [comment]
Yeah, the problem is the plugin is ignoring the contacts import is disabled and sending the request for user’s friends anyway. So the solution is to either use the contacts feature and get the permission for your app on facebook, or for someone to add the logic to the code.

**Comment by alexxgathp** [comment]
Specifically, user_friends should probably be removed here, and then added in only if the user enabled the contacts feature.

https://github.com/miled/wordpress-social-login/blob/9c5987a661d88ac44dde70285dfc87b8b9594d63/hybridauth/library/src/Provider/Facebook.php#L45

**Comment by Bigspecialk** [comment]
Thank you for the help. I tried looking for that file in the Plugin and couldn't find it to edit. Do you know if it would be called something else?

**Comment by loichnh** [comment]
+1

**Comment by s3w47m88** [comment]
+1 The Plugin is unusable without this issue being resolved.

**Comment by marcelomoreira1973** [comment]
There is a filter to fix this.
add_filter( 'wsl_hook_alter_provider_scope', 'virtus_wsl_hook_alter_provider_scope', 10, 2 );

Example
function virtus_wsl_hook_alter_provider_scope( $provider_scope, $provider ) {
    if ( $provider == 'Facebook' ) {
        $provider_scope_new = str_replace( ', user_friends', '', $provider_scope );
         return $provider_scope_new;      
    }
    return $provider_scope;
}

**Comment by Sarvarkhuja** [comment]
As @alexxgathp said " user_friends " should be removed. but the directory was changed you can find it in wsl.providers.php:line 46 in the directory wordpress-social-login\wordpress-social-login\includes\settings
`		"default_api_scope" => "email, public_profile, user_friends", `

plugin version is 2.3.3

**Comment by omerdes** [comment]
delete  " , public_profile, user_friends","
