### ISSUE TITLE
Problem with Facebook Registration / too long User URLs

### ISSUE THREAD

**Issue by benthebear** [miled/wordpress-social-login#269]
Hi there,

we ran into a problem with the Facebook Registration today, which might interest you …

Until yesterday the User-URLs Facebook delivered via the API looked like this …

https://www.facebook.com/app_scoped_user_id/1947300111000000/

Since today, the look like this …

https://www.facebook.com/app_scoped_user_id/YXNpZADpBWEdncWpIYjQtUWNRelMzdWV2eDBXUTlBUTYwWmlfMnJLQjlRenB5djU1bVJKc3pPRFFkaTloY1ZAObkthN1ZAQOEVZAZATFibGlSNk5FTGFkaqwerwewerwasdfasdfasdfasdfasdfasdf/

(I anonymized the Links.)

… which is too long for Wordpress'  user_url field in the wp_users table (which is only 100 Character Varchar), and it is not validated anywhere in the plugin or the core. 

As the user-fields are hookable, we were able to fix it quite fast, but you might want to adjust that in the core of the plugin, as I assume that it's broken pretty much everywhere …

All the best!
ben_

**Comment by JimBoone** [comment]
I ran into the same problem -  It looks like if the new user registration for Facebook is broken that it would be generating a much higher level of activity.

**Comment by lastorset** [comment]
Duplicate of #263 (which has a workaround!).

**Comment by benthebear** [comment]
Thanks!
