### ISSUE TITLE
Problem with version 3

### ISSUE THREAD

**Issue by ghost** [miled/wordpress-social-login#278]
Hello,

I updated the plugin to version 3, but I met some problems with some social networks, including:

Facebook, Google, Instagram and Tumblr

**Facebook releases the following error:**

> URL blocked: This redirect failed because the redirect URI was not added to the whitelist in the app's client OAuth settings. Make sure that the OAuth client and the web access are active and add all app domains as valid OAuth redirect URIs.

**Google:**

> 400. That's an error.
> 
> Error: invalid_request
> 
> Missing required parameter: scope
> 
> Learn more
> Request Details
> 
>     response_type code =
>     client_id = 1075918617123-lvnhssemg3ljd1el8d8ru8ghipt7gdpu.apps.googleusercontent.com
>     redirect_uri = https: //www.sviluppomania.com/wp-content/plugins/wordpress-social-login/hybridauth/? hauth.done = Google
>     scope =
>     access_type = offline
>     state = HA-ZGHQBJ6WXPVO1S9IF4KD8ME7CA2T0LU3RN5Y
> 
> That's all we know.

By chance are the callback url changed?

I have these:

**ex:** wp-content / plugins / wordpress-social-login / hybridauth /? hauth.done = Instagram

**Comment by onliniak** [comment]
Google works now. Facebook is Facebook … ones works, ones not. Instagram and Tumblir I don't check.

For Google type url and enter, otherwise it will not be saved. New version use https://skri.ga/wp-content/plugins/wordpress-social-login/hybridauth/callbacks/google.php

**Comment by sviluppomania** [comment]
For Windows?

**Comment by onliniak** [comment]
Sorry, I don`t understand.

There are 2 options: Google don't save your url (ex. you click save before you enter url) or wrong urls. On the other hand it may be temporary error in old version. Latest version works … ¾ works.

Step by step :

1. https://console.developers.google.com/apis/credentials?project=name
2. Edit login/credencials.
3. https://www.sviluppomania.com → domain
4.  https://www.sviluppomania.com/wp-content/plugins/wordpress-social-login/hybridauth/callbacks/google.php → redirect.
5. Check ones again.

Similar on other platforms.
