### ISSUE TITLE
Twitter does not accept anymore callbacks with a query string

### ISSUE THREAD

**Issue by rformato** [miled/wordpress-social-login#281]
You can see I've added two callback URLS, and the one with the query string is considered invalid.

Any workaround?

![immagine](https://user-images.githubusercontent.com/969336/45264396-35e46c80-b43c-11e8-9802-35a2e179ae3f.png)

**Comment by jmessy919** [comment]
I think it's safe to say the developer has abandoned this plugin and it will need to be forked in order to continue accommodating Twitter.

**Comment by picard102** [comment]
If you leave the query string off the end, it will still work.

**Comment by jmessy919** [comment]
> If you leave the query string off the end, it will still work.

You are right! I just tested it again and it worked.

**Comment by cesare190** [comment]
as soon as I put a "=" the url becomes invalid

**Comment by nabtron** [comment]
@cesare190 :

1. what's the exact url that you're entering?
2. does the error remain if you add value after =?
3. what's the twitter settings page exact url where you're adding this value?

**Comment by picard102** [comment]
> as soon as I put a "=" the url becomes invalid

You don't need it. Just use https://mywebsite.com/wp-content/plugins/wordpress-social-login/hybridauth/
