### ISSUE TITLE
Facebook Policy Warning for App

### ISSUE THREAD

**Issue by mdbootstrap** [miled/wordpress-social-login#283]
Hi, 

thanks for an awesome product. We've been using it for years but yesterday we have received following warning from Facebook, could you please assist us and help to solve the issue? 

Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.

During Login, your app is crashing or hanging excessively, creating a broken experience for people trying to use your app. To make sure this flow runs smoothly, check that you've integrated Facebook Login correctly. We recommend that you test Login on all integrations. If you have not already done so, please:

• We encourage you to test your Login integration following these steps here: https://developers.facebook.com/docs/facebook-login/testing-your-login-flow/
• Best Practices for Login can be found here: https://developers.facebook.com/docs/facebook-login/best-practices

**Comment by inspire22** [comment]
Did you ever get this resolved?  Facebook seems to use some automated checks for these, and I'm not sure they are all working correctly...

**Comment by IDFDeveloper** [comment]
I just received this kind of mail from facebook. I am working on android platform but `facebook_app_id` is also used in iOS as well as Web also. I have read that provided document on that link and everything is same as explained. I have checked my facebook SDK version and other all configuration but everything is fine as specified on that link. so let me know that have you solved this issue or not. I have checked [this post](https://openedx.atlassian.net/browse/LEARNER-5474) also.

**Comment by MilanWmt** [comment]
@IDFDeveloper How to fix this issue. Because I am facing the same issue from the Facebook side.
Plz help me to how to resolve this

**Comment by IDFDeveloper** [comment]
> @IDFDeveloper How to fix this issue. Because I am facing the same issue from the Facebook side.
> Plz help me to how to resolve this

I haven't found any proper solution regarding this. I have added user as tester for testing and testing the app whenever i testing the app. There is no any other effect on my project from facebook side. If you will get any solution then please share it here !

**Comment by sandeep14** [comment]
Please some one help to know how to communicate with fb team to know what exact issue they are facing
