### ISSUE TITLE
Reddit avatar not being shown when registering

### ISSUE THREAD

**Issue by novalex** [miled/wordpress-social-login#285]
Hi!

I ran into an issue when trying to register with Reddit, more specifically the avatar is not loading properly. The src for the img element is empty.

![reddit avatar issue](https://user-images.githubusercontent.com/10091929/46288739-6dec5480-c58f-11e8-8ee7-4382c6cb25c2.PNG)

I am using WP Social Login 2.3.3 with BuddyPress 3.2.0.

**Comment by nova-ind** [comment]
Was able to get the Reddit avatar to show up by adding
`$this->user->profile->photoURL = @ $response->icon_img;`
on line 196 of hybridauth/Hybrid/Providers/Reddit.php.
