### ISSUE TITLE
Facebook App Review failed

### ISSUE THREAD

**Issue by dawidadach** [miled/wordpress-social-login#297]
Dear, 
I have just received that Facebook has proactively reviewed my app which is used to work with Social Login plugin and it has failed to pass following checks: 

The review team wasn't able to:
Confirm your app works and follows Facebook guidelines
Load and easily use your test app
Verify Facebook Login button is visible in your screencast and adheres to Facebook brand guidelines
Reproduce use case details and follow step-by-step instructions
Use of user_gender follows established Facebook guidelines
Use of user_friends follows established Facebook guidelines
Use of user_age_range follows established Facebook guidelines
Use of user_link follows established Facebook guidelines

Are you planning to do something about that? Are those scopes really required?

**Comment by jaredpalmer** [comment]
I have the same issue. Can we make scopes editable?

**Comment by zemas-inc** [comment]
Scopes is editable you can change it trough theme's function.php hook:
in e.x. 
function wsl_lower_default_permissons( $provider_scope, $provider ){
    if( 'facebook' == strtolower( $provider ) ){
        $provider_scope = 'email'; // should not be empty or it will be overwritten
    }
    return $provider_scope;
}
add_filter( 'wsl_hook_alter_provider_scope', 'wsl_lower_default_permissons', 10, 2 );
source: http://miled.github.io/wordpress-social-login/developer-api-snippets.html

so it also do not require app review:
Which permissions require review?
Review is not required to ask for the two basic permissions: public_profile and email.
Review is required to ask for any other permissions when people log into your app
source: https://developers.facebook.com/docs/facebook-login/review/what-is-login-review/

**Comment by fjakop** [comment]
WSL asks by default for "user_friends", which requires review. It would be nice if this scope is only requested when contacts is enabled in wsl.
