### ISSUE TITLE
LinkedIn Not Working

### ISSUE THREAD

**Issue by ZainoLabs** [miled/wordpress-social-login#299]
LinkedIn suddenly stopped working for me. All yesterday I was getting a 500 error. Today just a blank screen. Checking to see if there is a known issue.

Other services work fine.

**Comment by dinesh4monto** [comment]
Yes, I am also facing the issue. Here is the response:
```response: { "errorCode": 0, "message": "This resource is no longer available under v1 APIs", "requestId": "MQXGMKOQWK", "status": 410, "timestamp": 1556193353283 }```

**Comment by mattrabe** [comment]
@dinesh4monto Did you happen to create a patch? I'm about to start working on a PR to use v2, based on [their docs](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context), unless you've already got one handy...

**Comment by fclaussen** [comment]
I just tested his fork and it works. I would not have labeled it as linkedin V2 but it works.

**Comment by dinesh4monto** [comment]
@mattrabe No, I didn't work on the patch.

**Comment by mattrabe** [comment]
I can also confirm that we are able to login using LinkedIn again, after using the jobstertheme form. @aleximbir do you plan to make a PR back to this repo? My team and I intend to work with your forked version of the plugin this week toward a final solution for a client site, and would be happy to provide commits for anything we find.

We agree with fclaussen that this should be named just "linkedin" and REPLACE the previous linkedin integration - that way this will not be a breaking change for existing users, and furthermore the v1 API is no longer online so need to support it.

**Comment by aleximbir** [comment]
@fclaussen @mattrabe 

I have already made a PR to this repo.

For my needs, I use both versions of Linkedin because some of my clients have created the Linkedin application using v1 and these applications no longer work with the v2 implementation.

Feel free to remove v1 and replace v2 tags before merging.

**Comment by mattrabe** [comment]
@aleximbir Thank you for your response and PR!

Is there some way to continue using the V1 LinkedIn API that I am not aware of? I have existing clients that had old V1 integrations as well, and as of a May 1 [LinkedIn took v1 offline](https://engineering.linkedin.com/blog/2018/12/developer-program-updates) - this broke their integrations and required us to upgrade to v2, which as far as I can tell is a requirement for all users moving forward. If there's something I am missing please let me know.

**Comment by aleximbir** [comment]
@mattrabe 

I noticed that I didn't have the last commits from the WSL repo and some of my code for LinkedIn v2 is not compatible with the latest changes; I will close this PR and I will come back with another after the fixes.

About v1, I don't know but I see that one of my old application is still working with Linkedin v1 and is not working with Linkedin v2 and one of my new application is not working with v1 but is able to make the register and log in with v2

**Comment by aleximbir** [comment]
Everything is ok now with Linkedin v2 and new callback URL format
PR: https://github.com/miled/wordpress-social-login/pull/323

**Comment by mattrabe** [comment]
@aleximbir Great.

@miled My team intends to create a couple PRs over the next week - the first to bring hybridauth up to 3.0.0, the second to follow up on aleximbir's work on linkedin v2 api

**Comment by mattrabe** [comment]
pull request #328
