### ISSUE TITLE
Google+ APIs being shutdown on March 7, 2019

### ISSUE THREAD

**Issue by rafa0383** [miled/wordpress-social-login#300]
Google Announced that on March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019. (https://developers.google.com/+/api-shutdown)

All calls to people.get method of Google+ Api should migrate the more comprehensive Google Sign-in authentication system. (https://developers.google.com/identity/)

**Comment by oleonard** [comment]
It would be great to know if this is being actively worked on or whether we should start looking for another solution. Thanks!

**Comment by prabhjot2991** [comment]
I am new to Github but looks like developer has made some commitments - 

https://github.com/miled/wordpress-social-login/commit/791c5f4bca58af94f47cfccaaa6e72839fa0763f

Although, I have looked into the plugin and changelog is empty- "What's new on WSL 3.0.1..."

**Comment by oleonard** [comment]
> [791c5f4](https://github.com/miled/wordpress-social-login/commit/791c5f4bca58af94f47cfccaaa6e72839fa0763f)

Thanks, that's very promising!

**Comment by VidSocial** [comment]
I hope we can get a solution before they shut it down

**Comment by ktecho** [comment]
Anyone tried this to see if it works?

**Comment by seansweda** [comment]
791c5f4 works for me, however it does require updating your callback URLs
