### ISSUE TITLE
Error 200 with Instagram Login

### ISSUE THREAD

**Issue by ilhantekir** [miled/wordpress-social-login#301]
Hello everyone,

I am using the WSL Plugin, Version 2.3.3

I am getting the following error, when logging into my website with Instagram:

WordPress Social Login Endpoint.
200. Thanks for stopping by!

This error messages comes up both when user is already registered (and only wants to login) or if he does not have an user account yet.

The error only comes up if user also has to login to Instagram on the computer. If the user has already done the login on instagram.com, the login process works properly. This is however not very often the case as most users only use instagram on their mobile devices.

I have already checked the support forum (http://miled.github.io/wordpress-social-login/troubleshooting.html) and was told that it is not actually an issue. However, since I am not able to get around this around, it has become one for me.

Has anyone experienced something similar and / or does someone know how to solve the issue?

A big thank you in advance for your help!

**Comment by edmondoddy** [comment]
Dear @ilhantekir ,

How did you manage to add Instagram login? I see only 3 option in plugin settings, Facebook, Google+ and Twitter...

**Comment by sfatih** [comment]
Hi,
In the authorization box if you use different languages except English it will reject the request. So you should change your browser language or you should add language parameter to authorization link.

_https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=code&hl=en_

Important point is adding &hl=en parameter.
