### ISSUE TITLE
Google - Error 404

### ISSUE THREAD

**Issue by gonzalesc** [miled/wordpress-social-login#309]
Hi.
It allows to login in gmail and accept the permissions, but when back to website it shows a 404 error.

...wp-content/plugins/wordpress-social-login-master/hybridauth/callbacks/google.php?state=HA-F4HTJP9DVUGMLYC2NEXS37O6QRIWB801KZA5&code=4/DAHdRKY-JzHSNrgZC4fX1tZsexoI5pkloI0XsZPrDQL357cY5iOBft8dJYPWEIrz6hiKanjwHCSsv7uR-7TjW3E&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email

Regards

**Comment by kelaskakap** [comment]
I got same issue here. Please..

**Comment by gonzalesc** [comment]
Hi @kelaskakap . I changed to other plugin.

Regards
