### ISSUE TITLE
[ Google ] Hybridauth config does not exist on the given path.

### ISSUE THREAD

**Issue by gonzalesc** [miled/wordpress-social-login#310]
Hi
Im using the last version 3.x and when I do login with Google, but when it return from Google, it show this message.

`Hybridauth config does not exist on the given path.`

I see this error is set in `hybridauth/library/src/Hybridauth.php`

The `wsl_get_provider_config_from_session_storage()` funtcion is send a empty variable because the `SESSION ` variable is not defined

```
function wsl_get_provider_config_from_session_storage($provider)
{
	$provider = strtolower($provider);

    if(isset($_SESSION['wsl:' . $provider . ':config']))
    {
        return (array) $_SESSION['wsl:' . $provider . ':config'];
    }
}
```

Some idea please?
ss

**Comment by jmeler** [comment]
Hi @gonzalesc, did you find a solution for this error?
