### ISSUE TITLE
Add hooks into the content

### ISSUE THREAD

**Issue by daneloctober** [miled/wordpress-social-login#311]
Hi! My client wanted to edit the html within the includes/widgets/wsl.users.gateway.php but there was no way to do so. It was actually just CSS, but the usual way recommended by WordPress (https://codex.wordpress.org/Customizing_the_Login_Form) does not work since this page is basically "isolated". I didn't have a choice except to edit the plugin file.

Please add action hooks within the html content. Thank you!

**Comment by GodisaFighter** [comment]
Hi there! 

Interested to know how you went with this as I have a custom registration form that needs to be submitted which will create the user according to another specific plugin. 

Are you able to assist me with a way to have this custom registration form completed during the login process prior to creation? 

This would help us launch our site much better!

Are you in a position to help us? 

Regards, 

Robert Hunt
