### ISSUE TITLE
Is this plugin still supported?

### ISSUE THREAD

**Issue by tamara-m** [miled/wordpress-social-login#316]
Hi Miled and contributors,

I use the plugin on a couple of sites, official WP repo version, and since it's been 2 years and 3 major releases without an update, I was wondering what the plan for the plugin is.

With recent Google API changes, it seems the Google integration has also stopped working.

This repo seems to be active, but warns not to be used, so some indication of what the status is here would be really helpful so one can plan accordingly.

Thank you very much for your time and for putting an awesome plugin out there for the community, I've always loved it.

**Comment by shashankmestry** [comment]
@miled Need to update this plugin on officially. There are lots of changes in Google and FB graph APIs. those needs to be taken care of. Are you planning to release the latest plugin soon?

**Comment by jambots** [comment]
https://developer.linkedin.com/blog/posts/2018/redirecting-oauth-uas
https://wordpress.org/support/topic/linkedin-api-v1-deprecated-on-1st-march-2019/

This plugin uses https://api.linkedin.com/uas/oauth/ and v1 api calls.
