### ISSUE TITLE
Hook extra registration fields problem [ URGENT ]

### ISSUE THREAD

**Issue by Mazda140** [miled/wordpress-social-login#317]
My client want to force users to insert their phone numbers after social login. I found that this plugin help my with that. But here is the problem.
I use Theme My Login with it and i add extra field for phone number in registration and it worked fine in the form. When i set  Hook extra registration fields to yes i go through the social signing and the message for completion " New to our website?
Please fill in your information in the form below. Once completed, you will be able to automatically sign into our website through your Google ID." Appear and it must show the phone number and password under it. But nothing show up i thought it is a problem about the form it self but i tried to create account then it show an error for me that i must enter phone number and password so the do(registration_form) work but WHY the fields hidden?

It is not show in the HTML ether.
So what should i do?

**Comment by shihchau** [comment]
I also have similar problem when I switched on extra registration fields. 

It kept returning "ERROR: Please enter a password." but there is no password field below. 

Is there anyone who knows how to solve it?

**Comment by shihchau** [comment]
Oh, I think it is probably because some fields require permission from FB.
