### ISSUE TITLE
WSL end-points

### ISSUE THREAD

**Issue by ghost** [miled/wordpress-social-login#321]
Hello,
Today i explore WSL 3.0.1. on my development site. and i found this (on image)

![image](https://user-images.githubusercontent.com/26438200/58484115-c21cf800-8161-11e9-9db9-3cf8d5004055.png)

but on right table it say FAIL!

Error: WSL end-points urls are not reachable.

If your hosting provider is using mod_security then request to whitelist your domain (HostGator and GoDaddy are known to have mod_security enabled)

This error may also happen when a .htaccess file is set to prevent direct access to the WordPress plugins directory.

Whether you are using mod_security or a .htaccess file, WSL will requires these two urls to be white-listed:

https://XXX.com/login/
https://XXX.com/wp-content/plugins/wordpress-social-login/hybridauth/

**Comment by sviluppomania** [comment]
@miled
