### ISSUE TITLE
WSL v3.0.1 conflict with WordPress Site health tool REST API Curl error

### ISSUE THREAD

**Issue by jimi008** [miled/wordpress-social-login#333]
> The REST API request failed due to an error.
> Error: [] cURL error 28: Operation timed out after 10003 milliseconds with 0 bytes received

WSL 3.0.1 conflict with WordPress REST API and CURL. WordPress Sitehealth tool not working and throw curl error. After disabling WSL issue fixed and error gone. 

After debugging, Its seems this is something related to 'PHP Sessions' and to fix this for now install **WordPress Native PHP Sessions** plugin and then activate WSL, this time it will not cause any error. 

> May be need to implement PHP’s native session handler, backed by the WordPress database. This allows to safely use PHP $_SESSIONs in a distributed environment where PHP’s default tempfile storage just won’t work.

[https://wordpress.org/plugins/wp-native-php-sessions/](url)

**Comment by sviluppomania** [comment]
Hello @jimi008 
Thanks to you I solved the problem, but is there a solution without using the plugin?

Also I have this problem:

![image](https://user-images.githubusercontent.com/26438200/77214994-1e4a7180-6b12-11ea-91e3-acc4170970a8.png)

**Comment by sviluppomania** [comment]
@miled

**Comment by sviluppomania** [comment]
@jimi008
