### ISSUE TITLE
twitter is not accepting GET parameters on callback url no more - so cannot use it to login with plugin

### ISSUE THREAD

**Issue by YammYcoding** [miled/wordpress-social-login#336]
The app for twitter social login is generating callback url with a GET parameter like that: ?hauth.done=Twitter

The problem is that twitter is not accepting get parameters on callback urls anymore, therefore I cannot use wp social plugin to login using twitter…

So, do you guys have a fix for that? WP Social Plugin update, maybe?

I tried removing the parameter and leaving the rest, with or without / in the end, but it didn't solve the problem either.

**Comment by s-sols** [comment]
I faced with the same situation. I did the same trick and it didn't help until i disabled my page cache with URL parameters.
