### ISSUE TITLE
Google OAuth only works for the first 100 users

### ISSUE THREAD

**Issue by codingdudecom** [miled/wordpress-social-login#341]
Hi,

I've successfully setup the plugin with Google OAuth. I've setup the consent screen and got the app verified. But after 100 users have registered via the Google button, no extra users can register as it says that the app is not yet verified (even though it is)

I think this is because there is a 100 users cap on the Google OAuth API. Any idea how to raise this limit?

Here's how it looks now in my GCP console: https://i.stack.imgur.com/jvOTW.jpg

**Comment by GianCastle** [comment]
Same happens to me

Hey, @codingdudecom . Did you find a workaround to this?

**Comment by codingdudecom** [comment]
Yes, I've found a solution. I simply switched to a different plugin called Super Socializer. Things work fine now (see here: https://www.mockofun.com/)
