### ISSUE TITLE
Legacy People API has not been used in project...

### ISSUE THREAD

**Issue by EvanAgee** [miled/wordpress-social-login#344]
Getting this error when attempting to auth. Looks like the project may use a legacy version of the People API.

![image](https://user-images.githubusercontent.com/1692674/76804265-db06a080-67a9-11ea-9320-7e7a4c8b4045.png)

**Comment by damisadam** [comment]
I also facing same issue

"Legacy People API has not been used in project 559723433610 before or it is disabled."

Please respond ASAP. Thanks

**Comment by persiej** [comment]
Guys, Just download latest version from here Github and replace with older version manually in your plugin folder it will work,
Cheers,

**Comment by cybersholt** [comment]
it sure would have been nice if there was a big red notice on the site "http://miled.github.io/wordpress-social-login/" with something like if you plan on using google download the beta.

**Comment by miled** [comment]
It would be nice indeed. 

I will go with green tho.
