### ISSUE TITLE
Odnoklassniki public key

### ISSUE THREAD

**Issue by arturdilan** [miled/wordpress-social-login#352]
How to add public key in Odnoklassniki settings so that it works. ?

**Comment by s-sols** [comment]
Current implementation supports using only App ID or App Key. The ability to add both keys were added in https://github.com/miled/wordpress-social-login/pull/350.

**Comment by dinka05** [comment]
😉

**Comment by s-sols** [comment]
The stable branch based on 3.0.1 is located in https://github.com/s-sols/wordpress-social-login/tree/stable and working plugin can be downloaded from there by 'Clone or download'.
