### ISSUE TITLE
Unspecified error.

### ISSUE THREAD

**Issue by sahidul99** [miled/wordpress-social-login#353]
Hi I am getting unspecified error ,[Here I added a short vedio of my configuration and error details](https://drive.google.com/file/d/1uiBWyPPHGYuLrZOiD6ceXmGeKflJgvUW/view?usp=sharing)

**Comment by s-sols** [comment]
Have you been using the stable 3.0.1 version?

**Comment by sahidul99** [comment]
> Have you been using the stable 3.0.1 version?

latest version is 2.3.3 ,where do you got 3.0.1 version?

**Comment by s-sols** [comment]
It can be got from [last work commit](https://github.com/miled/wordpress-social-login/tree/cb71e6cde0661b5bfad8c4d09d5b9b888e80f62c) by 'Clone or download' button.
