### ISSUE TITLE
Outdated/deprecated scope in Google provider

### ISSUE THREAD

**Issue by kospl** [miled/wordpress-social-login#358]
Using plugin with Google provider we see that Google+ scope is used:

`https://accounts.google.com/signin/oauth?client_id=[ID].apps.googleusercontent.com&redirect_uri=https://...com/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done%3DGoogle&response_type=code&scope=profile+https://www.googleapis.com/auth/plus.profile.emails.read&access_type=offline&o2v=1&as=..`

This particular scope:
> https://www.googleapis.com/auth/plus.profile.emails.read

per Google+ [shutdown documentation](https://developers.google.com/+/scopes-shutdown) is listed as `Deprecated Scope` and should be changed to one of:

- `https://www.googleapis.com/auth/profile.emails.read`
- `email`

**Comment by s-sols** [comment]
Have you tried last stable 3.0.1 version?

**Comment by kospl** [comment]
@s-sols we're on latest stable release, according to https://wordpress.org/plugins/wordpress-social-login/ it's `2.3.3`.

If it's fixed in newer version, what is ETA for Wordpress distribution?

**Comment by s-sols** [comment]
You can download 3.0.1 by changelist: https://github.com/miled/wordpress-social-login/tree/cb71e6cde0661b5bfad8c4d09d5b9b888e80f62c.

**Comment by kospl** [comment]
Fixed by adding `wsl_hook_alter_provider_scope` filter and replacing scopes just to `profile` and `email`:

```
// set lower permissions for sign in with Google: request only profile (for name) and email address
function wsl_lower_default_permissons($provider_scope, $provider)
{
    if ('google' === strtolower($provider))
    {
        $provider_scope = 'profile email'; 
    }

    return $provider_scope;
}

add_filter('wsl_hook_alter_provider_scope', 'wsl_lower_default_permissons', 10, 2);
```
