### ISSUE TITLE
hybridauth config does not exist on the given path

### ISSUE THREAD

**Issue by motgon01** [miled/wordpress-social-login#386]
Hi there,

I'm getting the entitle error message only when browsing from smartphones (iOS & Android), any idea what is going on? I already checked with the hosting server admin and we found no issue with the server settings.

This is the host server log we are getting: 
93.173.99.195 - - [22/Jan/2022:10:01:46 +0000] "GET /wp-content/plugins/wordpress-social-login/hybridauth/callbacks/google.php?state=HA-3IPC7FRQ4Y0K9VETDG1UBWA5LZ2H6XM8NSOJ&code=4%2F0AX4XfWj-QXq3SjaNVwfkJh50xySAbO08mXzknlrlQqUxfGfK0p3V1vMKOePQtYo_9-3lhg&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=1&prompt=none HTTP/1.1" 200 434 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1"

When browsing from desktop PC - no issue. All works fine.

Any advice would be highly appreciated.

Thank you

**Comment by ulziibat-n** [comment]
I faced this problem too.
@motgon01 did you solve this problem? Do you have any solution for it?
