### ISSUE TITLE
WSL end-points

### ISSUE THREAD

**Issue by hrace009** [miled/wordpress-social-login#47]
Hello,
Today i explore WSL 2.2.3 on my development site. and i found this (on image)
![capture](https://cloud.githubusercontent.com/assets/7691118/4838629/8e28165a-5fed-11e4-9baf-7e229c7e8dd9.JPG)
i still don't understand what it mean.
i try to access the link given, and i can see some message
![capture2](https://cloud.githubusercontent.com/assets/7691118/4838644/e5a57bc0-5fed-11e4-8330-92bc60c41aae.JPG) but on right table it say FAIL!

Error: WSL end-points urls are not reachable.

If your hosting provider is using mod_security then request to whitelist your domain (HostGator and GoDaddy are known to have mod_security enabled)

This error may also happen when a .htaccess file is set to prevent direct access to the WordPress plugins directory.

Whether you are using mod_security or a .htaccess file, WSL will requires these two urls to be white-listed:
1. http://hrace009.XXX.com/login/
2. http://hrace009.XXX.com/wp-content/plugins/wordpress-social-login/hybridauth/

btw i am not using GoDaddy, i host it on my personal server (Dedicated) using Apache and FastCGI PHP 5.4

**Comment by sviluppomania** [comment]
Hi @miled 

I have the same problem. How can I solve it?

Also by activating / deactivating your plugin I found that WordPress reports these two errors (related to WordPress Social Login):

> **The REST API encountered an error**
> 
> The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.
> 
> The REST API request failed due to an error.
> Error: [] cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received


> **Your site could not complete a loopback request**
> 
> Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.
> 
> The loopback request to your site failed, this means features relying on them are not currently working as expected.
> Error: [] cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received


How come and how can I solve them?

![image](https://user-images.githubusercontent.com/26438200/77213315-b5abc680-6b0a-11ea-9bd4-b979fdc74452.png)
