### ISSUE TITLE
changing username in create new user form has no effect

### ISSUE THREAD

**Issue by gxrahul** [miled/wordpress-social-login#55]
After user is redirected back, on create new account form, username change has no effect.
After a little digging I found the bug in the file " wordpress-social-login/includes/widgets/wsl.users.gateway.php
", line no 45. 

$requested_user_login        = isset( $_REQUEST["user_login"] ) ? trim( $_REQUEST["user_login"] ) : $hybridauth_user_login;

should be:

$requested_user_login        = isset( $_REQUEST["user_name"] ) ? trim( $_REQUEST["user_name"] ) : $hybridauth_user_login;

Form is using "user_name" but when getting the data wrong field name is used.

**Comment by hubdotcom** [comment]
Confirmed, submitting a patch for this now

**Comment by hubdotcom** [comment]
@gxrahul user_login is actually the corresponding WordPress field name and is used correctly throughout so we update the incorrect form field name that is sending the data on #L573
