### ISSUE TITLE
User Moderation = Admin Approval doesn't work

### ISSUE THREAD

**Issue by HenryHzz** [miled/wordpress-social-login#57]
Hi,
I am using the latest WSL (2.2.3) with User Moderation set to Admin Approval (and has the latest Theme My Login installed - 6.3.10).  The Admin never gets an email message saying there is a pending request for approval.  However, I am able to "fix" the issue by using a hook to WSL in my theme's function.php.  If you add these code before the do_action on the hook, it should fix the problem permanently.  Here is my hook:
function HH_TML_mod_notice($in_user_id, $in_provider, $in_hy_user_prof) {
    $HH_level = get_option( 'wsl_settings_bouncer_new_users_moderation_level' );
    if( $HH_level == 101 ) {
        @ Theme_My_Login_User_Moderation::new_user_activation_notification( $in_user_id );
    }
    elseif( $HH_level == 102 ) {
        @ Theme_My_Login_User_Moderation::new_user_approval_admin_notification( $in_user_id );
    }
    return;
} // end HH_TML_moderation_notices
add_action('wsl_hook_process_login_after_wp_insert_user', 'HH_TML_mod_notice', 10, 3);

**Comment by skynet** [comment]
:+1:
