### ISSUE TITLE
TWITCH.TV - User Authentication requests Stream Key - Security concern

### ISSUE THREAD

**Issue by Jacklifear** [miled/wordpress-social-login#64]
Currently when you connect your twitch account through the application, you use a scope the requests the email and the stream key. I have a lot of people showing concerns about giving their stream key to my database cause that means I can (if I had ill intents) use their stream key to stream on their channel.  This is a major security flaw that should at least be considered.

![image](https://cloud.githubusercontent.com/assets/10401883/6316639/0c5d0fca-b9f4-11e4-8044-ab792b4c10a1.png)

This looks like it's using scope channel_read instead of user_read

Source - https://github.com/justintv/Twitch-API/blob/master/authentication.md#scopes
channel_read: Read access to non-public channel information, including email address and stream key.
user_read: Read access to non-public user information, such as email address.

Is there a way to make it work for user_read instead?

Thanks!

**Comment by hubdotcom** [comment]
As an immediate change, you can update this file to prevent the additional permission request:
wordpress-social-login/hybridauth/Hybrid/Providers/TwitchTV.php

simply change
> public $scope = "user_read channel_read";
to
> public $scope = "user_read";

@miled it doesn't appear the authentication is using the channel data - can you confirm and if so could this permission be removed from the code?

**Comment by miled** [comment]
@hubdotcom Yes it make sense to remove that extra scope.

FWIW, it's also possible to remove it through this filter:

```php
function wsl_lower_default_permissons( $provider_scope, $provider )
{
    if( 'twitchtv' == strtolower( $provider ) )
    {
        $provider_scope = 'user_read';
    }
 
    return $provider_scope;
}
 
add_filter( 'wsl_hook_alter_provider_scope', 'wsl_lower_default_permissons', 10, 2 );
```
http://miled.github.io/wordpress-social-login/developer-api-snippets.html

**Comment by hubdotcom** [comment]
Nice snippet! I'll put in a pull request :)
