### ISSUE TITLE
ajax

### ISSUE THREAD

**Issue by 7aduta** [miled/wordpress-social-login#66]
i'm trying to login by ajax but i couldn't find any solution to it 
can you help my to provide an ajax example to login by facebook & twitter & google 
i'm trying to integrate the plugin with phonegap facebook login plugin so i could give user access to site data and register from app

**Comment by miled** [comment]
AFAIK it's impossible. The [library](https://github.com/hybridauth/hybridauth/) we're using doesn't allow [Implicit Grant flow](https://tools.ietf.org/html/draft-ietf-oauth-v2-30#section-1.3.2).
