### ISSUE TITLE
USing with Hide My Wp

### ISSUE THREAD

**Issue by Masterrenny** [miled/wordpress-social-login#76]
Hello,

I have the Hide My Wp installed for security reasons but your plugin doesnt seem to be compatible with it? 

It uses rewites to mask the actual roots but your plugin doesnt use them directories, how could i make it so it masks the wp-login.php...etc

**Comment by miled** [comment]
That's because the URL is [hard coded](https://github.com/miled/wordpress-social-login/blob/master/wp-social-login.php#L92-L99) inside the plugin.

I'll take a look at HMW and see if it's possible to resolve that.

**Comment by Masterrenny** [comment]
Is there anything you need to know? I can cost the rewites if you need them? what file(s) would i need to edit?
