### ISSUE TITLE
Can I have the WSL widget on top of login form?

### ISSUE THREAD

**Issue by jenseo** [miled/wordpress-social-login#88]
Hey,
I love WSL and it works great on my site. Would like to ask though: Would it be possible to move the WSL widget so that it appears over the normal login form, instead of under? 

Would be more logical for me to encourage the users to log in the easiest way.

Possible?

Thanks a lot for an awesome plugin!

**Comment by ihorvorotnov** [comment]
WSL hooks into `login_form` action and in the login form it's the only suitable hook available. Just checked the `wp-login.php` code and haven't found any other hook. The only solution I think of is using CSS `flex` properties to switch the form and widget display positions. But that sounds like a dirty hack (which it actually is).
