### ISSUE TITLE
Vulnerability on /Hybrid/thirdparty/LinkedIn/LinkedIn.php

### ISSUE THREAD

**Issue by ellocofray** [miled/wordpress-social-login#89]
Hello.
I'm being successfully attacked with a mailbot.
Investigating in apache logs i found that a file is created after a POST in /Hybrid/thirdparty/LinkedIn/LinkedIn.php

my knowledge about this is very limited but, coud you check?

125.227.170.68 - - [18/May/2015:12:26:29 -0300] "POST /wp-content/plugins/wordpress-social-login/hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php HTTP/1.1" 200 498 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"
125.227.170.68 - - [18/May/2015:12:26:37 -0300] "GET /wp-content/cache/supercache/site/comienza-el-congreso-de-los-chicos/inc.php HTTP/1.1" 200 47 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"

THANKS!

**Comment by espellcaste** [comment]
Wow, that's not good, for the plugin, I mean.

**Comment by ihorvorotnov** [comment]
@ellocofray you should probably file an issue in <a href="https://github.com/hybridauth/hybridauth">Hybrid Auth</a> repo.
