### ISSUE TITLE
Application Secret in setup view is auto completed and shown in clear text

### ISSUE THREAD

**Issue by joelpet** [miled/wordpress-social-login#90]
I believe that an Application Secret should be treated with the same care as a password since it grants access to the corresponding application. Currently it is shown in clear text when setting up the networks plus the input field allows auto completion, which causes the browser (at least mine) to save it and suggest it elsewhere too.

If I am not mistaken, this is where the input field is defined:
https://github.com/miled/wordpress-social-login/blob/08ea6addc3bf65671d8fd1c54f0f2ea13e6456bd/includes/admin/components/networks/wsl.components.networks.setup.php#L154

What are your thoughts on this?

Thank you.

**Comment by beatdroppin** [comment]
joelpet if you are wishing for that simply add something like this to the existing code 

<input type="text" autocomplete="off"/>
or  Alternative:
<form autocomplete="off" … >

**Comment by joelpet** [comment]
Thank you for your response @beatdroppin. My intention with creating this issue was to reach a consensus on whether application secrets should be considered equal to passwords in the sense that it should not be shown in clear text and thereby neither should it be auto completed. If such treatment of application secrets is deemed good practice, then I would much rather see the plugin officially patched than me applying a patch locally. In the other case where the current implementation is considered sufficiently secure I will just happily go on using the plugin as is. :)

**Comment by ihorvorotnov** [comment]
Pretty interesting suggestion. I'll check with other plugins and devs and see if there's any standard or consensus on this.
