### ISSUE TITLE
Console for Testing

### ISSUE THREAD

**Issue by espellcaste** [miled/wordpress-social-login#96]
Another improvement to consider to add into the plugin. 

A console to allow testing without real user information. Facebook, for example, doesn't allow testing with a domain different from the application.

So if you have a vagrant box with the domain vvv.teste and on the application www.yourwesbite.com, it'll not accept it.

**Comment by ihorvorotnov** [comment]
Facebook supports Test Apps, (see here)[https://developers.facebook.com/docs/apps/test-apps]. I'm using them for development and local server, works fine with local domains like `mylocalsite.dev` (or whatever name and extension you use).

**Comment by espellcaste** [comment]
That's good, I was not aware of that. Quick suggestion, put this information on the documentation. Other developers using the plugin at first might not be aware of that.

**Comment by ihorvorotnov** [comment]
Sounds good to me. Will add this along with new PR I'm going to submit in a day or two, If @miled won't add it faster.

**Comment by espellcaste** [comment]
=1 (y)
